// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6WUjysk_a3yocx2iSJLUi5TUT8AX3esY',
    appId: '1:60865903848:android:6fda31291f05b6598a5d5d',
    messagingSenderId: '60865903848',
    projectId: 're-miles-dfm',
    storageBucket: 're-miles-dfm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXSEnsFN9g0D4Alp3Y18MgjVdt5YYST4U',
    appId: '1:60865903848:ios:4cf36ad5290196fe8a5d5d',
    messagingSenderId: '60865903848',
    projectId: 're-miles-dfm',
    storageBucket: 're-miles-dfm.firebasestorage.app',
    androidClientId: '60865903848-ifeje8oo05qgrcfritgho1eefeaoh8l7.apps.googleusercontent.com',
    iosClientId: '60865903848-1b2qqj7b6cn681ng7f1li77jfmn3gk3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.majh',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAws50DdvJkUsWwPbRf2wNk0m9s-LIQ7Fk',
    appId: '1:60865903848:web:de7bf9f344f97cf48a5d5d',
    messagingSenderId: '60865903848',
    projectId: 're-miles-dfm',
    authDomain: 're-miles-dfm.firebaseapp.com',
    storageBucket: 're-miles-dfm.firebasestorage.app',
    measurementId: 'G-0ZZWFKS41B',
  );

}